name: showcase
version: 0.0.1

authors:
  - Igor Borges <igor@borges.me>

description: Generates documentation screenshots of your widgets.
homepage: https://github.com/Igor1201/showcase

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  source_gen: ^0.9.0

dev_dependencies:
  test: ^1.0.0
